server:
  port: 8080

spring:
  application:
    name: abrigo-quatro-patas-ms
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

springdoc:
  version: "@springdoc.version@"
  swagger-ui:
    use-root-path: true
    urls:
      - name: adoption
        url: adoption-ms/v3/api-docs
      - name: client
        url: client-ms/v3/api-docs
      - name: ong
        url: ong-ms/v3/api-docs
      - name: pet
        url: pet-ms/v3/api-docs
      - name: voluntary
        url: voluntary-ms/v3/api-docs