server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: email-ms
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: abrigo.quatro.patas@gmail.com
    password: lydlqdyufupmmuai
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true