
server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: voluntary-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/voluntary-ms