server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ong-ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/ong_db


